dist: xenial
language: go

go:
  - "1.12"

git:
  depth: 1

install: true

before_script:
  - env GO111MODULE=on make mocks

script:
  - env GO111MODULE=on make build
  - env GO111MODULE=on make test
